/*!

EasyTV Matchmaker 

Copyright 2017-2020 Center for Research & Technology - HELLAS


The research leading to these results has received funding from
the European Union's H2020-ICT-2016-2, ICT-19-2017 Media and content convergence
under grant agreement no. 761999.
*/

//Generated 28 Feb 17:50:22

var stat = {}
stat.entryCount = 0;
stat.clusters = [
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 2,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/common/contrast": 14,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/application/cs/ui/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/speed": 76,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 6,
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/volume": 70,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 14,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 7,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#FE8B5C",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/common/volume": 99
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "home",
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 97,
        "http://registry.easytv.eu/context/time": "11:53:10"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["es"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 1,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -28,
        "http://registry.easytv.eu/common/contrast": 59,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4300,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 66,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 0.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/common/content/audio/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 10,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/volume": 75,
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 18,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 6.7,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 160,
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "CA",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1200,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 2900,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#2FD0BE",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/common/volume": 51
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "class",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 77,
        "http://registry.easytv.eu/context/time": "07:51:57"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 0,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "ES",
        "http://registry.easytv.eu/common/contrast": 72,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/application/cs/ui/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/speed": 84,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/common/content/audio/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/tts/audio/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "CA",
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/volume": 13,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 98,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#C8CBCE",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/common/volume": 67
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": "visual task",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 20,
        "http://registry.easytv.eu/context/time": "08:55:35"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["it"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 10,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "GR",
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -46,
        "http://registry.easytv.eu/common/contrast": 29,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 3500,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 69,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 8.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/tts/audio/language": "EN",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 20,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "GR",
        "http://registry.easytv.eu/application/cs/audio/volume": 7,
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 93,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 0.7,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 147,
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1430,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 4400,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#C5A860",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 1.5,
        "http://registry.easytv.eu/common/volume": 37
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "living room",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 57,
        "http://registry.easytv.eu/context/time": "10:38:58"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["gr"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": ["ca"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 9,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "GR",
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": 6,
        "http://registry.easytv.eu/common/contrast": 81,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4700,
        "http://registry.easytv.eu/application/cs/ui/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/speed": 19,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 4.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "15",
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -29,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "CA",
        "http://registry.easytv.eu/application/cs/audio/volume": 63,
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 72,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 5.7,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/tts/audio/quality": 1,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 83,
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1540,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 3200,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#6468D0",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/common/volume": 61
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": "detailed work",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 4,
        "http://registry.easytv.eu/context/time": "07:37:56"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 8,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/common/contrast": 51,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 78,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "15",
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/common/content/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 25,
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 24,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/Size": 39,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#7840DB",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 97,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/tts/audio/quality": 5,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#A32E0D",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#B932E8",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/common/volume": 60
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "visual task",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 97,
        "http://registry.easytv.eu/context/time": "09:16:54"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 7,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "ES",
        "http://registry.easytv.eu/common/contrast": 43,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 14,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/volume": 62,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/Size": 89,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#C39523",
        "http://registry.easytv.eu/application/tts/audio/volume": 32,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 1,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#CA5592",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#B2E88E",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/common/volume": 22
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "hallway",
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 2,
        "http://registry.easytv.eu/context/time": "08:52:35"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 6,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "CA",
        "http://registry.easytv.eu/common/contrast": 19,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 50,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/common/content/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 39,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/Size": 36,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#679343",
        "http://registry.easytv.eu/application/tts/audio/volume": 4,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#8BBBB4",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#C16028",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/common/volume": 54
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": "grocery",
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 20,
        "http://registry.easytv.eu/context/time": "03:23:55"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 5,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "CA",
        "http://registry.easytv.eu/common/contrast": 72,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 24,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/common/content/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 21,
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/cs/audio/volume": 27,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/Size": 63,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#48E603",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 26,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 5,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#EDA23D",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#91DC1F",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/common/volume": 50
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": "overcast day",
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 23,
        "http://registry.easytv.eu/context/time": "05:18:37"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["es"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 4,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "CA",
        "http://registry.easytv.eu/common/contrast": 77,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/application/cs/ui/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/speed": 5,
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 18,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 24,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#DFA04C",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 27,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 1.7,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": false,
        "http://registry.easytv.eu/application/tts/audio/quality": 5,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#7E1BAE",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "CA",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1030,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#B7252F",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -3,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 1400,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 8.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -15,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/Size": 73,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "GR",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 47,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 4700,
        "http://registry.easytv.eu/common/volume": 86
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": "overcast day",
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 86,
        "http://registry.easytv.eu/context/time": "06:08:41"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": ["gr"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 3,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "ES",
        "http://registry.easytv.eu/common/contrast": 80,
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 87,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 44,
        "http://registry.easytv.eu/application/tts/audio/language": "GR",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 28,
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 3,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/tts/audio/quality": 6,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#9EF489",
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/common/volume": 31
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": "demanding visual task",
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 38,
        "http://registry.easytv.eu/context/time": "00:10:03"
    }
}
];

module.exports = stat;
