/*!

EasyTV Matchmaker 

Copyright 2017-2020 Center for Research & Technology - HELLAS


The research leading to these results has received funding from
the European Union's H2020-ICT-2016-2, ICT-19-2017 Media and content convergence
under grant agreement no. 761999.
*/

//Generated 13 Feb 10:59:43

var stat = {}
stat.entryCount = 0;
stat.clusters = [
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "gr",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 5,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 17,
        "http://registry.easytv.eu/application/cs/ui/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/speed": 93,
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 36,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 65,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#115D15",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 1,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 6.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#28AA67",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1430,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#51F5AB",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -20,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 5100,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 1.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -6,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 4,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 86,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 2800,
        "http://registry.easytv.eu/common/volume": 46
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": 26,
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 49,
        "http://registry.easytv.eu/context/time": "05:29:10"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "gr"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 6,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "ES",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 14,
        "http://registry.easytv.eu/application/cs/ui/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/speed": 36,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 47,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 41,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#06CF39",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 39,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 6.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#4DB7AE",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 880,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#023203",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 1.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": 38,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 5400,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 9.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/common/content/audio/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -1,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "face-detection",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 28,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 0,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 53,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 4700,
        "http://registry.easytv.eu/common/volume": 22
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 51,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 2,
        "http://registry.easytv.eu/context/time": "02:50:07"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 7,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "ES",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/common/contrast": 97,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 43,
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 4,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/cs/audio/volume": 4,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#F0E53D",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 24,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 4.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 8,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#2D68C6",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 550,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#848CDD",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -30,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 3200,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 9.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "15",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/language": "EN",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -15,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "face-detection",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 99,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 103,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": false,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 3000,
        "http://registry.easytv.eu/common/volume": 41
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 72,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 78,
        "http://registry.easytv.eu/context/time": "02:57:53"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["es"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 8,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "GR",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/common/contrast": 63,
        "http://registry.easytv.eu/application/cs/ui/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/speed": 4,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 7,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "CA",
        "http://registry.easytv.eu/application/cs/audio/volume": 37,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#1CF36E",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 36,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 6.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 6,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#7D3688",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1540,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#1EC417",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": 24,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 1700,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 2.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 28,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 15,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 189,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 4300,
        "http://registry.easytv.eu/common/volume": 21
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 25,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 67,
        "http://registry.easytv.eu/context/time": "04:38:25"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "ca",
            "gr",
            "it",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 9,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "CA",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 96,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 18,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 47,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 28,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#0F8E39",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 46,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 3.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#8EA8C2",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 680,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#C336B5",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": 14,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 2200,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 1.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "15",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 29,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "face-detection",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 59,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 208,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 3700,
        "http://registry.easytv.eu/common/volume": 34
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": 74,
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 84,
        "http://registry.easytv.eu/context/time": "09:26:26"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 10,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "CA",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 96,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 94,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 18,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "CA",
        "http://registry.easytv.eu/application/cs/audio/volume": 58,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#800DC9",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 61,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 10.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "en",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#3C2FEE",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1470,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#F82B84",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -12,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 2600,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 4.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 46,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": true,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 96,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "GR",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 154,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 2400,
        "http://registry.easytv.eu/common/volume": 48
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 28,
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 42,
        "http://registry.easytv.eu/context/time": "05:36:42"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": ["es"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 0,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/common/contrast": 72,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 84,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 17,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "CA",
        "http://registry.easytv.eu/application/cs/audio/volume": 89,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#FE8BD2",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 98,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 5.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#477D0D",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "EN",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1540,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#C8CBCE",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 2.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": 33,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 3300,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 2.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "15",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 2,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/common/content/audio/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/language": "EN",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 44,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "face-detection",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 84,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "CA",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 3,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 143,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 3200,
        "http://registry.easytv.eu/common/volume": 67
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": 53,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 96,
        "http://registry.easytv.eu/context/time": "04:25:18"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["it"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 1,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "GR",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/common/contrast": 22,
        "http://registry.easytv.eu/application/cs/ui/language": "EN",
        "http://registry.easytv.eu/application/tts/audio/speed": 75,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": true,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 4,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 96,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#CD5D63",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 37,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 9.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 3,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ca",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#B0B284",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 320,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#52C6CF",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 1.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -15,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4800,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 2.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/language": "CA",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": 40,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 34,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": false,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 3,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 188,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 3000,
        "http://registry.easytv.eu/common/volume": 4
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 21,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 15,
        "http://registry.easytv.eu/context/time": "02:34:39"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": ["gr"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 2,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 8,
        "http://registry.easytv.eu/application/cs/ui/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/speed": 68,
        "http://registry.easytv.eu/application/control/voice": false,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 17,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 79,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#FA475B",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 16,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 6.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 6,
        "http://registry.easytv.eu/application/cs/cc/subtitles": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#21F744",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 1110,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#10449B",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 1.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -19,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4800,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 0.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "GR",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -9,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 81,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 106,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 2700,
        "http://registry.easytv.eu/common/volume": 93
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": 14,
        "http://registry.easytv.eu/context/location": "ca",
        "http://registry.easytv.eu/context/proximity": 65,
        "http://registry.easytv.eu/context/time": "00:09:02"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [
            "gr",
            "es"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": [
            "ca",
            "it"
        ],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false
    },
    "user_id": 3,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "GR",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": true,
        "http://registry.easytv.eu/common/contrast": 59,
        "http://registry.easytv.eu/application/cs/ui/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/speed": 55,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": false,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 9,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "ES",
        "http://registry.easytv.eu/application/cs/audio/volume": 7,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#CE45B7",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": true,
        "http://registry.easytv.eu/application/tts/audio/volume": 67,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 3.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 2,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "en",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#252F9B",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "GR",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": false,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 840,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#FC2D3C",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -30,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4300,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 2.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "ES",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -7,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "slow",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "face-detection",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 77,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "ES",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "none",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 2,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 57,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 2200,
        "http://registry.easytv.eu/common/volume": 49
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "pc",
        "http://registry.easytv.eu/context/light": 44,
        "http://registry.easytv.eu/context/location": "it",
        "http://registry.easytv.eu/context/proximity": 84,
        "http://registry.easytv.eu/context/time": "06:39:11"
    }
},
{
    "user_content": {
        "http://registry.easytv.eu/application/cs/audio/track": [],
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": ["it"],
        "http://registry.easytv.eu/application/cs/accessibility/detection/face": true,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": true
    },
    "user_id": 4,
    "user_profile": {"user_preferences": {"default": {"preferences": {
        "http://registry.easytv.eu/application/cs/audio/track": "EN",
        "http://registry.easytv.eu/application/hbbtv/screen/reader": false,
        "http://registry.easytv.eu/common/contrast": 10,
        "http://registry.easytv.eu/application/cs/ui/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/speed": 95,
        "http://registry.easytv.eu/application/control/voice": true,
        "http://registry.easytv.eu/application/cs/cc/audio/subtitle": true,
        "http://registry.easytv.eu/application/cs/ui/audioAssistanceBasedOnTTS": false,
        "http://registry.easytv.eu/application/cs/ui/text/magnification/scale": false,
        "http://registry.easytv.eu/application/cs/accessibility/detection/text": false,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/font/size": 28,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiLanguage": "EN",
        "http://registry.easytv.eu/application/cs/audio/volume": 68,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/color": "#AABB91",
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/background": false,
        "http://registry.easytv.eu/application/tts/audio/volume": 50,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/qFactor": 7.7,
        "http://registry.easytv.eu/application/tts/audio/quality": 1,
        "http://registry.easytv.eu/application/cs/cc/subtitles": true,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/language": "ar",
        "http://registry.easytv.eu/application/cs/cc/subtitles/background/color": "#DC1FB0",
        "http://registry.easytv.eu/application/cs/accessibility/sign/language": "ES",
        "http://registry.easytv.eu/application/cs/accessibility/detection/sound": true,
        "http://registry.easytv.eu/application/cs/audio/eq/low/pass/frequency": 620,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles/position": "up",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/color": "#307BF0",
        "http://registry.easytv.eu/application/cs/accessibility/magnification/scale": 3.5,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/gain": -30,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/frequency": 4300,
        "http://registry.easytv.eu/application/cs/audio/eq/high/pass/qFactor": 3.7,
        "http://registry.easytv.eu/application/tts/audio/voice": "male",
        "http://registry.easytv.eu/application/cs/ui/text/size": "20",
        "http://registry.easytv.eu/common/display/screen/enhancement/cursor/size": 1,
        "http://registry.easytv.eu/application/cs/accessibility/detection/character": false,
        "http://registry.easytv.eu/common/content/audio/language": "CA",
        "http://registry.easytv.eu/application/tts/audio/language": "ES",
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/gain": -50,
        "http://registry.easytv.eu/application/hbbtv/screen/reader/speed": "normal",
        "http://registry.easytv.eu/application/cs/audio/eq": false,
        "http://registry.easytv.eu/application/cs/accessibility/enhancement/image/type": "none",
        "http://registry.easytv.eu/application/cs/accessibility/detection/text/reader": true,
        "http://registry.easytv.eu/application/cs/cc/subtitles/font/size": 72,
        "http://registry.easytv.eu/application/hbbtv/cc/subtitles": false,
        "http://registry.easytv.eu/application/cs/cc/subtitles/language": "EN",
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlType": "gaze_control",
        "http://registry.easytv.eu/application/cs/ui/vibration/touch": true,
        "http://registry.easytv.eu/application/control/csGazeAndGestureControlCursorGuiTextSize": 1,
        "http://registry.easytv.eu/application/cs/audio/eq/low/shelf/frequency": 146,
        "http://registry.easytv.eu/application/cs/accessibility/audio/description": true,
        "http://registry.easytv.eu/application/cs/audio/eq/high/shelf/frequency": 4000,
        "http://registry.easytv.eu/common/volume": 98
    }}}},
    "user_context": {
        "http://registry.easytv.eu/context/device": "modile",
        "http://registry.easytv.eu/context/light": 93,
        "http://registry.easytv.eu/context/location": "gr",
        "http://registry.easytv.eu/context/proximity": 35,
        "http://registry.easytv.eu/context/time": "04:00:33"
    }
}
];

module.exports = stat;
